### ISSUE TITLE
Build error in version 1.3.2

### ISSUE THREAD

**Issue by euroboy** [yonat/BatteryView#4]
I just updated the pod to version 1.3.2 and got an error on build, see the attached screenshot.
<img width="1311" alt="Screen Shot 2019-05-29 at 17 37 40" src="https://user-images.githubusercontent.com/6330272/58566119-a9334600-8238-11e9-9b85-808ac0a5dd41.png">

**Comment by yonat** [comment]
Ah, Xcode 10.2! Fixed in 1.3.3.
