### ISSUE TITLE
The Privacy Manifest is Defective

### ISSUE THREAD

**Issue by phoney** [yonat/BatteryView#7]
**Description of the problem:**
The privacy manifest is missing some keys. 

NSPrivacyCollectedDataTypes
NSPrivacyTrackingDomains
NSPrivacyAccessedAPITypes

I think these can all be empty arrays but they need to be present.

Please see IQKeyboardManagerSwift for an example of a simple privacy manifest.

https://github.com/hackiftekhar/IQKeyboardManager/blob/master/IQKeyboardManagerSwift/PrivacyInfo.xcprivacy

I see this error in my Privacy Report:

![Screenshot 2024-04-01 at 4 31 54 PM](https://github.com/yonat/BatteryView/assets/3106038/4083fb6f-82d0-4dde-853a-86ebe7af105e)

**Minimal project that reproduces the problem (so I'll be able to figure out how to fix it):**
[link to a Minimal Reproducible Example as described at https://ootips.org/yonat/repex ]

I assume that the Privacy Report can be generated with the BatteryViewDemo and latest Xcode (but I didn't try it).

**Comment by phoney** [comment]
@yonat I've made a PR to address this. After merging please bump the version so I can pull this down with cocoa pods. Thanks.

**Comment by yonat** [comment]
Thanks for the PR, please use version 1.4.2.
